CREATE TABLE IF NOT EXISTS TITLES
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR                                 NOT NULL,
    city VARCHAR                                 NOT NULL,
    CONSTRAINT pk_title PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS REPORT_PATTERNS
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type     VARCHAR                                 NOT NULL,
    title_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_reportPattern PRIMARY KEY (id),
    CONSTRAINT FK_REPORT_PATTERNS_ON_TITLES FOREIGN KEY (title_id) REFERENCES titles (id)
);

CREATE TABLE IF NOT EXISTS SECTIONS
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number_section    INTEGER                                 NOT NULL,
    heading           VARCHAR                                 NOT NULL,
    report_pattern_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_sections PRIMARY KEY (id),
    CONSTRAINT FK_SECTIONS_ON_REPORT_PATTERNS FOREIGN KEY (report_pattern_id) REFERENCES report_patterns (id)
);

CREATE TABLE IF NOT EXISTS DRAWINGS_SECTIONS
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type        VARCHAR                                 NOT NULL,
    number      INTEGER                                 NOT NULL,
    description VARCHAR                                 NOT NULL,
    sections_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_drawingSection PRIMARY KEY (id),
    CONSTRAINT FK_DRAWINGS_SECTIONS_ON_SECTIONS FOREIGN KEY (sections_id) REFERENCES sections (id)
);

CREATE TABLE IF NOT EXISTS COMBINED_COLUMNS
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    column_first  INTEGER                                 NOT NULL,
    column_second INTEGER                                 NOT NULL,
    name          VARCHAR                                 NOT NULL,
    CONSTRAINT pk_combinedColumns PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS TABLES
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                VARCHAR                                 NOT NULL,
    combined_columns_id BIGINT,
    CONSTRAINT pk_tables PRIMARY KEY (id),
    CONSTRAINT FK_TABLES_ON_COMBINED_COLUMNS FOREIGN KEY (combined_columns_id) REFERENCES combined_columns (id)
);

CREATE TABLE IF NOT EXISTS COLUMNS
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number    INTEGER                                 NOT NULL,
    name      VARCHAR                                 NOT NULL,
    tables_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_column PRIMARY KEY (id),
    CONSTRAINT FK_COLUMNS_ON_TABLES FOREIGN KEY (tables_id) REFERENCES tables (id)
);

CREATE TABLE IF NOT EXISTS SUBSECTIONS
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number      FLOAT                                   NOT NULL,
    heading     VARCHAR                                 NOT NULL,
    text        VARCHAR,
    tables_id   BIGINT,
    sections_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_subsections PRIMARY KEY (id),
    CONSTRAINT FK_SUBSECTIONS_ON_TABLES FOREIGN KEY (tables_id) REFERENCES tables (id),
    CONSTRAINT FK_SUBSECTIONS_ON_SECTIONS FOREIGN KEY (sections_id) REFERENCES sections (id)
);

