CREATE TABLE IF NOT EXISTS TITLES
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR                                 NOT NULL,
    city VARCHAR                                 NOT NULL,
    CONSTRAINT pk_title PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS REPORT_PATTERNS
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type     VARCHAR                                 NOT NULL,
    title_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_reportPattern PRIMARY KEY (id),
    CONSTRAINT FK_REPORT_PATTERNS_ON_TITLES FOREIGN KEY (title_id) REFERENCES titles (id)
);

CREATE TABLE IF NOT EXISTS SECTIONS
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number            INTEGER                                 NOT NULL,
    heading           VARCHAR                                 NOT NULL,
    report_pattern_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_sections PRIMARY KEY (id),
    CONSTRAINT FK_SECTIONS_ON_REPORT_PATTERNS FOREIGN KEY (report_pattern_id) REFERENCES report_patterns (id)
);

CREATE TABLE IF NOT EXISTS DRAWINGS
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type        VARCHAR                                 NOT NULL,
    number      INTEGER                                 NOT NULL,
    description VARCHAR                                 NOT NULL,
    sections_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_drawing PRIMARY KEY (id),
    CONSTRAINT UQ_DRAWINGS UNIQUE (number, description),
    CONSTRAINT FK_DRAWINGS_ON_SECTIONS FOREIGN KEY (sections_id) REFERENCES sections (id)
);

CREATE TABLE IF NOT EXISTS SUBSECTIONS
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number         FLOAT                                   NOT NULL,
    heading        VARCHAR                                 NOT NULL,
    text           VARCHAR,
    paragraph      VARCHAR,
    place          VARCHAR,
    deviation_size VARCHAR,
    conclusion     VARCHAR,
    sections_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_subsections PRIMARY KEY (id),
    CONSTRAINT FK_SUBSECTIONS_ON_SECTIONS FOREIGN KEY (sections_id) REFERENCES sections (id)
);

CREATE TABLE IF NOT EXISTS TABLES
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR                                 NOT NULL,
    text           VARCHAR,
    subsections_id BIGINT,
    CONSTRAINT pk_tables PRIMARY KEY (id),
    CONSTRAINT FK_TABLES_ON_SUBSECTIONS FOREIGN KEY (subsections_id) REFERENCES subsections (id)
);

CREATE TABLE IF NOT EXISTS COMBINED_COLUMNS
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first  INTEGER                                 NOT NULL,
    second INTEGER                                 NOT NULL,
    name   VARCHAR                                 NOT NULL,
    CONSTRAINT pk_combinedColumns PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS COLUMNS
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number              INTEGER                                 NOT NULL,
    name                VARCHAR                                 NOT NULL,
    table_id            BIGINT                                  NOT NULL,
    combined_columns_id BIGINT,
    CONSTRAINT pk_column PRIMARY KEY (id),
    CONSTRAINT FK_COLUMNS_ON_TABLES FOREIGN KEY (table_id) REFERENCES tables (id),
    CONSTRAINT FK_COLUMNS_COLUMNS_ON_COMBINED FOREIGN KEY (combined_columns_id) REFERENCES combined_columns (id)
);

CREATE TABLE IF NOT EXISTS SUB_TABLES
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR                                 NOT NULL,
    table_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_subTable PRIMARY KEY (id),
    CONSTRAINT UQ_SUB_TABLES UNIQUE (name, table_id),
    CONSTRAINT FK_SUB_TABLE_ON_TABLE FOREIGN KEY (table_id) REFERENCES tables (id)
);

CREATE TABLE IF NOT EXISTS ELEMENTS
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type         VARCHAR                                 NOT NULL,
    point        INTEGER,
    name         VARCHAR                                 NOT NULL,
    is_no_defect VARCHAR                                 NOT NULL,
    table_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_element PRIMARY KEY (id),
    CONSTRAINT UQ_ELEMENTS UNIQUE (name, type),
    CONSTRAINT FK_ELEMENTS_ON_TABLES FOREIGN KEY (table_id) REFERENCES tables (id)
);

CREATE TABLE IF NOT EXISTS SUB_ELEMENTS
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR                                 NOT NULL,
    element_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_subElement PRIMARY KEY (id),
    CONSTRAINT UQ_SUB_ELEMENTS UNIQUE (name, element_id),
    CONSTRAINT FK_SUB_ELEMENTS_ON_ELEMENTS FOREIGN KEY (element_id) REFERENCES elements (id)
);

CREATE TABLE IF NOT EXISTS DEFECTS
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR                                 NOT NULL,
    element_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_defect PRIMARY KEY (id),
    CONSTRAINT UQ_DEFECTS UNIQUE (name, element_id)
);